[env:rpipico2]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipico2
framework = arduino
board_build.core = earlephilhower
board_build.f_cpu = 196608000L

; Opciones de compilación extremas para Audio DSP (M33 + FPU)
build_flags = 
    -Wstack-usage=256

    -Ofast
    -fstack-protector
    -fno-exceptions
    -fno-rtti
    -fno-use-cxa-atexit
    -mcpu=cortex-m33
    -mfpu=fpv5-sp-d16
    -D OPTIMIZE_HARDWARE
    -D MAX_EFFECTS_SIMULTANEOUS=4
    -D PIN_I2S_BCLK=14
    -D PIN_I2S_LRCK=15
    -D PIN_I2S_DOUT=16
    -D PIN_I2S_DIN=17
    -D PIN_I2S_MCLK=21
    -D PIN_OLED_SDA=0
    -D PIN_OLED_SCL=1
    -D PIN_ENC1_A=2
    -D PIN_ENC1_B=3
    -D PIN_ENC1_SW=4
    -D PIN_ENC2_A=5
    -D PIN_ENC2_B=6
    -D PIN_ENC2_SW=7
    -D PIN_ENC3_A=8
    -D PIN_ENC3_B=9
    -D PIN_ENC3_SW=10
    -D PIN_ENC_PARA_A=18
    -D PIN_ENC_PARA_B=19
    -D PIN_ENC_PARA_SW=20
    -D PIN_FS1=11
    -D PIN_FS2=12
    -D PIN_FS3=13
    -D PIN_FS4=22
    -D PIN_MASTER_VOL=26
    -D PIN_EXPRESSION=27
    -D PIN_NEOPIXEL=28

; Librerías globales (si hubieran)
lib_deps =
    adafruit/Adafruit SSD1306 @ ^2.5.9
    adafruit/Adafruit GFX Library @ ^1.11.9

lib_extra_dirs = lib_DSP
