from collections import defaultdict
from skidl import Pin, Part, Alias, SchLib, SKIDL, TEMPLATE

from skidl.pin import pin_types

SKIDL_lib_version = '0.0.1'

main_build = SchLib(tool=SKIDL).add_parts(*[
        Part(**{ 'name':'RP2350B', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'RP2350B'}), 'ref_prefix':'U', 'fplist':['Package_DFN_QFN:QFN-80-1EP_10x10mm_P0.4mm_EP3.4x3.4mm'], 'footprint':'LCC-23_18x23.5mm', 'keywords':'RPi Pico USB QSPI I2C UART ADC SC1510', 'description':'A microcontroller by Raspberry Pi, dual CPU architecture (ARM Cortex-M33 / RISC-V Hazard3), 150MHz, no flash, 520KB SRAM, 12 PIO state machines, VQFN-80', 'datasheet':'https://datasheets.raspberrypi.com/rp2350/rp2350-datasheet.pdf', 'pins':[
            Pin(num='10',name='DVDD',func=pin_types.PWRIN,unit=1),
            Pin(num='38',name='GPIO30',func=pin_types.BIDIR,unit=1),
            Pin(num='39',name='GPIO31',func=pin_types.BIDIR,unit=1),
            Pin(num='40',name='GPIO32',func=pin_types.BIDIR,unit=1),
            Pin(num='42',name='GPIO33',func=pin_types.BIDIR,unit=1),
            Pin(num='43',name='GPIO34',func=pin_types.BIDIR,unit=1),
            Pin(num='44',name='GPIO35',func=pin_types.BIDIR,unit=1),
            Pin(num='45',name='GPIO36',func=pin_types.BIDIR,unit=1),
            Pin(num='46',name='GPIO37',func=pin_types.BIDIR,unit=1),
            Pin(num='47',name='GPIO38',func=pin_types.BIDIR,unit=1),
            Pin(num='48',name='GPIO39',func=pin_types.BIDIR,unit=1),
            Pin(num='49',name='GPIO40/ADC0',func=pin_types.BIDIR,unit=1),
            Pin(num='50',name='IOVDD',func=pin_types.PASSIVE,unit=1),
            Pin(num='51',name='DVDD',func=pin_types.PASSIVE,unit=1),
            Pin(num='52',name='GPIO41/ADC1',func=pin_types.BIDIR,unit=1),
            Pin(num='53',name='GPIO42/ADC2',func=pin_types.BIDIR,unit=1),
            Pin(num='54',name='GPIO43/ADC3',func=pin_types.BIDIR,unit=1),
            Pin(num='55',name='GPIO44/ADC4',func=pin_types.BIDIR,unit=1),
            Pin(num='56',name='GPIO45/ADC5',func=pin_types.BIDIR,unit=1),
            Pin(num='57',name='GPIO46/ADC6',func=pin_types.BIDIR,unit=1),
            Pin(num='58',name='GPIO47/ADC7',func=pin_types.BIDIR,unit=1),
            Pin(num='60',name='IOVDD',func=pin_types.PASSIVE,unit=1),
            Pin(num='61',name='VREG_AVDD',func=pin_types.PWRIN,unit=1),
            Pin(num='62',name='VREG_PGND',func=pin_types.PWRIN,unit=1),
            Pin(num='68',name='USB_OTP_VDD',func=pin_types.PWRIN,unit=1),
            Pin(num='69',name='QSPI_IOVDD',func=pin_types.PWRIN,unit=1),
            Pin(num='76',name='IOVDD',func=pin_types.PASSIVE,unit=1),
            Pin(num='1',name='GPIO4',func=pin_types.BIDIR,unit=1),
            Pin(num='2',name='GPIO5',func=pin_types.BIDIR,unit=1),
            Pin(num='3',name='GPIO6',func=pin_types.BIDIR,unit=1),
            Pin(num='4',name='GPIO7',func=pin_types.BIDIR,unit=1),
            Pin(num='5',name='IOVDD',func=pin_types.PWRIN,unit=1),
            Pin(num='6',name='GPIO8',func=pin_types.BIDIR,unit=1),
            Pin(num='7',name='GPIO9',func=pin_types.BIDIR,unit=1),
            Pin(num='8',name='GPIO10',func=pin_types.BIDIR,unit=1),
            Pin(num='9',name='GPIO11',func=pin_types.BIDIR,unit=1),
            Pin(num='11',name='GPIO12',func=pin_types.BIDIR,unit=1),
            Pin(num='12',name='GPIO13',func=pin_types.BIDIR,unit=1),
            Pin(num='13',name='GPIO14',func=pin_types.BIDIR,unit=1),
            Pin(num='14',name='GPIO15',func=pin_types.BIDIR,unit=1),
            Pin(num='15',name='IOVDD',func=pin_types.PASSIVE,unit=1),
            Pin(num='16',name='GPIO16',func=pin_types.BIDIR,unit=1),
            Pin(num='17',name='GPIO17',func=pin_types.BIDIR,unit=1),
            Pin(num='18',name='GPIO18',func=pin_types.BIDIR,unit=1),
            Pin(num='19',name='GPIO19',func=pin_types.BIDIR,unit=1),
            Pin(num='20',name='GPIO20',func=pin_types.BIDIR,unit=1),
            Pin(num='21',name='GPIO21',func=pin_types.BIDIR,unit=1),
            Pin(num='22',name='GPIO22',func=pin_types.BIDIR,unit=1),
            Pin(num='23',name='GPIO23',func=pin_types.BIDIR,unit=1),
            Pin(num='24',name='IOVDD',func=pin_types.PASSIVE,unit=1),
            Pin(num='25',name='GPIO24',func=pin_types.BIDIR,unit=1),
            Pin(num='26',name='GPIO25',func=pin_types.BIDIR,unit=1),
            Pin(num='27',name='GPIO26',func=pin_types.BIDIR,unit=1),
            Pin(num='28',name='GPIO27',func=pin_types.BIDIR,unit=1),
            Pin(num='29',name='IOVDD',func=pin_types.PASSIVE,unit=1),
            Pin(num='30',name='XIN',func=pin_types.INPUT,unit=1),
            Pin(num='31',name='XOUT',func=pin_types.OUTPUT,unit=1),
            Pin(num='32',name='DVDD',func=pin_types.PASSIVE,unit=1),
            Pin(num='33',name='SWCLK',func=pin_types.INPUT,unit=1),
            Pin(num='34',name='SWDIO',func=pin_types.BIDIR,unit=1),
            Pin(num='35',name='RUN',func=pin_types.INPUT,unit=1),
            Pin(num='36',name='GPIO28',func=pin_types.BIDIR,unit=1),
            Pin(num='37',name='GPIO29',func=pin_types.BIDIR,unit=1),
            Pin(num='41',name='IOVDD',func=pin_types.PASSIVE,unit=1),
            Pin(num='59',name='ADC_AVDD',func=pin_types.PWRIN,unit=1),
            Pin(num='63',name='VREG_LX',func=pin_types.PWROUT,unit=1),
            Pin(num='64',name='VREG_VIN',func=pin_types.PWRIN,unit=1),
            Pin(num='65',name='VREG_FB',func=pin_types.PASSIVE,unit=1),
            Pin(num='66',name='USB_DM',func=pin_types.BIDIR,unit=1),
            Pin(num='67',name='USB_DP',func=pin_types.BIDIR,unit=1),
            Pin(num='70',name='QSPI_SD3',func=pin_types.BIDIR,unit=1),
            Pin(num='71',name='QSPI_SCLK',func=pin_types.OUTPUT,unit=1),
            Pin(num='72',name='QSPI_SD0',func=pin_types.BIDIR,unit=1),
            Pin(num='73',name='QSPI_SD2',func=pin_types.BIDIR,unit=1),
            Pin(num='74',name='QSPI_SD1',func=pin_types.BIDIR,unit=1),
            Pin(num='75',name='~{QSPI_SS}',func=pin_types.OUTPUT,unit=1),
            Pin(num='77',name='GPIO0',func=pin_types.BIDIR,unit=1),
            Pin(num='78',name='GPIO1',func=pin_types.BIDIR,unit=1),
            Pin(num='79',name='GPIO2',func=pin_types.BIDIR,unit=1),
            Pin(num='80',name='GPIO3',func=pin_types.BIDIR,unit=1),
            Pin(num='81',name='GND',func=pin_types.PWRIN,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'Conn_01x20_Pin', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'Conn_01x20_Pin'}), 'ref_prefix':'J', 'fplist':[''], 'footprint':'TSSOP-14', 'keywords':'connector', 'description':'Generic connector, single row, 01x20, script generated', 'datasheet':'', 'pins':[
            Pin(num='1',name='Pin_1',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',name='Pin_2',func=pin_types.PASSIVE,unit=1),
            Pin(num='3',name='Pin_3',func=pin_types.PASSIVE,unit=1),
            Pin(num='4',name='Pin_4',func=pin_types.PASSIVE,unit=1),
            Pin(num='5',name='Pin_5',func=pin_types.PASSIVE,unit=1),
            Pin(num='6',name='Pin_6',func=pin_types.PASSIVE,unit=1),
            Pin(num='7',name='Pin_7',func=pin_types.PASSIVE,unit=1),
            Pin(num='8',name='Pin_8',func=pin_types.PASSIVE,unit=1),
            Pin(num='9',name='Pin_9',func=pin_types.PASSIVE,unit=1),
            Pin(num='10',name='Pin_10',func=pin_types.PASSIVE,unit=1),
            Pin(num='11',name='Pin_11',func=pin_types.PASSIVE,unit=1),
            Pin(num='12',name='Pin_12',func=pin_types.PASSIVE,unit=1),
            Pin(num='13',name='Pin_13',func=pin_types.PASSIVE,unit=1),
            Pin(num='14',name='Pin_14',func=pin_types.PASSIVE,unit=1),
            Pin(num='15',name='Pin_15',func=pin_types.PASSIVE,unit=1),
            Pin(num='16',name='Pin_16',func=pin_types.PASSIVE,unit=1),
            Pin(num='17',name='Pin_17',func=pin_types.PASSIVE,unit=1),
            Pin(num='18',name='Pin_18',func=pin_types.PASSIVE,unit=1),
            Pin(num='19',name='Pin_19',func=pin_types.PASSIVE,unit=1),
            Pin(num='20',name='Pin_20',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'TL072', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'TL072'}), 'ref_prefix':'U', 'fplist':['', ''], 'footprint':'DIP-8', 'keywords':'dual opamp', 'description':'Dual Low-Noise JFET-Input Operational Amplifiers, DIP-8/SOIC-8', 'datasheet':'http://www.ti.com/lit/ds/symlink/tl071.pdf', 'pins':[
            Pin(num='1',func=pin_types.OUTPUT,unit=1),
            Pin(num='2',name='-',func=pin_types.INPUT,unit=1),
            Pin(num='3',name='+',func=pin_types.INPUT,unit=1),
            Pin(num='5',name='+',func=pin_types.INPUT,unit=2),
            Pin(num='6',name='-',func=pin_types.INPUT,unit=2),
            Pin(num='7',func=pin_types.OUTPUT,unit=2),
            Pin(num='4',name='V-',func=pin_types.PWRIN,unit=3),
            Pin(num='8',name='V+',func=pin_types.PWRIN,unit=3)], 'unit_defs':[{'label': 'uA', 'num': 1, 'pin_nums': ['2', '1', '3']},{'label': 'uB', 'num': 2, 'pin_nums': ['7', '5', '6']},{'label': 'uC', 'num': 3, 'pin_nums': ['8', '4']}] }),
        Part(**{ 'name':'NE5532', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'NE5532'}), 'ref_prefix':'U', 'fplist':['', ''], 'footprint':'DIP-8', 'keywords':'dual opamp', 'description':'Dual Low-Noise Operational Amplifiers, DIP-8/SOIC-8', 'datasheet':'http://www.ti.com/lit/ds/symlink/ne5532.pdf', 'pins':[
            Pin(num='1',func=pin_types.OUTPUT,unit=1),
            Pin(num='2',name='-',func=pin_types.INPUT,unit=1),
            Pin(num='3',name='+',func=pin_types.INPUT,unit=1),
            Pin(num='5',name='+',func=pin_types.INPUT,unit=2),
            Pin(num='6',name='-',func=pin_types.INPUT,unit=2),
            Pin(num='7',func=pin_types.OUTPUT,unit=2),
            Pin(num='4',name='V-',func=pin_types.PWRIN,unit=3),
            Pin(num='8',name='V+',func=pin_types.PWRIN,unit=3)], 'unit_defs':[{'label': 'uA', 'num': 1, 'pin_nums': ['2', '1', '3']},{'label': 'uB', 'num': 2, 'pin_nums': ['6', '5', '7']},{'label': 'uC', 'num': 3, 'pin_nums': ['8', '4']}] }),
        Part(**{ 'name':'NJM4556A', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'NJM4556A'}), 'ref_prefix':'U', 'fplist':['', ''], 'footprint':'DIP-8', 'keywords':'dual opamp', 'description':'Dual High Current Operational Amplifier, DIP-8/DMP-8/SIP-8/SSOP-8', 'datasheet':'http://www.njr.com/semicon/PDF/NJM4556A_E.pdf', 'pins':[
            Pin(num='1',func=pin_types.OUTPUT,unit=1),
            Pin(num='2',name='-',func=pin_types.INPUT,unit=1),
            Pin(num='3',name='+',func=pin_types.INPUT,unit=1),
            Pin(num='5',name='+',func=pin_types.INPUT,unit=2),
            Pin(num='6',name='-',func=pin_types.INPUT,unit=2),
            Pin(num='7',func=pin_types.OUTPUT,unit=2),
            Pin(num='4',name='V-',func=pin_types.PWRIN,unit=3),
            Pin(num='8',name='V+',func=pin_types.PWRIN,unit=3)], 'unit_defs':[{'label': 'uA', 'num': 1, 'pin_nums': ['2', '1', '3']},{'label': 'uB', 'num': 2, 'pin_nums': ['5', '6', '7']},{'label': 'uC', 'num': 3, 'pin_nums': ['8', '4']}] }),
        Part(**{ 'name':'AP2112K-3.3', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'AP2112K-3.3'}), 'ref_prefix':'U', 'fplist':['Package_TO_SOT_SMD:SOT-23-5', 'Package_TO_SOT_SMD:SOT-23-5'], 'footprint':'SOT-25', 'keywords':'linear regulator ldo fixed positive', 'description':'600mA low dropout linear regulator, with enable pin, 3.8V-6V input voltage range, 3.3V fixed positive output, SOT-23-5', 'datasheet':'https://www.diodes.com/assets/Datasheets/AP2112.pdf', 'pins':[
            Pin(num='1',name='VIN',func=pin_types.PWRIN,unit=1),
            Pin(num='2',name='GND',func=pin_types.PWRIN,unit=1),
            Pin(num='3',name='EN',func=pin_types.INPUT,unit=1),
            Pin(num='4',name='NC',func=pin_types.NOCONNECT,unit=1),
            Pin(num='5',name='VOUT',func=pin_types.PWROUT,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'G5V-1', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'G5V-1'}), 'ref_prefix':'K', 'fplist':['Relay_THT:Relay_SPDT_Omron_G5V-1'], 'footprint':'DIP,12.5x7.5mm', 'keywords':'Single Pole Relay SPDT', 'description':'Ultra-miniature, Highly Sensitive SPDT Relay for Signal Circuits', 'datasheet':'http://omronfs.omron.com/en_US/ecb/products/pdf/en-g5v_1.pdf', 'pins':[
            Pin(num='1',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',func=pin_types.PASSIVE,unit=1),
            Pin(num='5',func=pin_types.PASSIVE,unit=1),
            Pin(num='6',func=pin_types.PASSIVE,unit=1),
            Pin(num='9',func=pin_types.PASSIVE,unit=1),
            Pin(num='10',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'AudioJack2', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'AudioJack2'}), 'ref_prefix':'J', 'fplist':[''], 'footprint':'', 'keywords':'audio jack receptacle mono phone headphone TS connector', 'description':'Audio Jack, 2 Poles (Mono / TS)', 'datasheet':'', 'pins':[
            Pin(num='S',func=pin_types.PASSIVE,unit=1),
            Pin(num='T',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'Conn_01x02', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'Conn_01x02'}), 'ref_prefix':'J', 'fplist':[''], 'footprint':'Connector_BarrelJack:BarrelJack_Horizontal', 'keywords':'connector', 'description':'Generic connector, single row, 01x02, script generated (kicad-library-utils/schlib/autogen/connector/)', 'datasheet':'', 'pins':[
            Pin(num='1',name='Pin_1',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',name='Pin_2',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'IRLML6401', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'IRLML6401'}), 'ref_prefix':'Q', 'fplist':['Package_TO_SOT_SMD:SOT-23', 'Package_TO_SOT_SMD:SOT-23'], 'footprint':'SOT-23', 'keywords':'P-Channel HEXFET MOSFET Logic-Level', 'description':'-4.3A Id, -12V Vds, 50mOhm Rds, P-Channel HEXFET Power MOSFET, SOT-23', 'datasheet':'https://www.infineon.com/dgdl/irlml6401pbf.pdf?fileId=5546d462533600a401535668b96d2634', 'pins':[
            Pin(num='1',name='G',func=pin_types.INPUT,unit=1),
            Pin(num='2',name='S',func=pin_types.PASSIVE,unit=1),
            Pin(num='3',name='D',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'D', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'D'}), 'ref_prefix':'D', 'fplist':[''], 'footprint':'DO-35', 'keywords':'diode', 'description':'Diode', 'datasheet':'', 'pins':[
            Pin(num='1',name='K',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',name='A',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'Conn_01x04', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'Conn_01x04'}), 'ref_prefix':'J', 'fplist':[''], 'footprint':'直插，P=2.54mm', 'keywords':'connector', 'description':'Generic connector, single row, 01x04, script generated (kicad-library-utils/schlib/autogen/connector/)', 'datasheet':'', 'pins':[
            Pin(num='1',name='Pin_1',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',name='Pin_2',func=pin_types.PASSIVE,unit=1),
            Pin(num='3',name='Pin_3',func=pin_types.PASSIVE,unit=1),
            Pin(num='4',name='Pin_4',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'R_Potentiometer', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'R_Potentiometer'}), 'ref_prefix':'RV', 'fplist':[''], 'footprint':'RES-ADJ-TH', 'keywords':'resistor variable', 'description':'Potentiometer', 'datasheet':'', 'pins':[
            Pin(num='1',name='1',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',name='2',func=pin_types.PASSIVE,unit=1),
            Pin(num='3',name='3',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'C', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'C'}), 'ref_prefix':'C', 'fplist':[''], 'footprint':'', 'keywords':'cap capacitor', 'description':'Unpolarized capacitor', 'datasheet':'', 'pins':[
            Pin(num='1',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'L', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'L'}), 'ref_prefix':'L', 'fplist':[''], 'footprint':'', 'keywords':'inductor choke coil reactor magnetic', 'description':'Inductor', 'datasheet':'', 'pins':[
            Pin(num='1',name='1',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',name='2',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'R', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'R'}), 'ref_prefix':'R', 'fplist':[''], 'footprint':'', 'keywords':'R res resistor', 'description':'Resistor', 'datasheet':'', 'pins':[
            Pin(num='1',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'WS2812B', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'WS2812B'}), 'ref_prefix':'D', 'fplist':['LED_SMD:LED_WS2812B_PLCC4_5.0x5.0mm_P3.2mm'], 'footprint':'LED_SMD:LED_WS2812B_PLCC4_5.0x5.0mm_P3.2mm', 'keywords':'RGB LED NeoPixel addressable', 'description':'RGB LED with integrated controller', 'datasheet':'https://cdn-shop.adafruit.com/datasheets/WS2812B.pdf', 'pins':[
            Pin(num='1',name='VDD',func=pin_types.PWRIN,unit=1),
            Pin(num='2',name='DOUT',func=pin_types.OUTPUT,unit=1),
            Pin(num='3',name='VSS',func=pin_types.PWRIN,unit=1),
            Pin(num='4',name='DIN',func=pin_types.INPUT,unit=1)], 'unit_defs':[] })])